export type Destination = {
  slug: string;
  name: string;
  country: string;
  region: string;
  category: "Sacred" | "Sufi heritage" | "Islamic history" | "Learning";
  arabic?: string;
  summary: string;
  significance: string;
  places: string[];
  etiquette: string;
  planning: string;
  source: string;
};

export const destinations: Destination[] = [
  { slug: "makkah", name: "Makkah al-Mukarramah", country: "Saudi Arabia", region: "Middle East", category: "Sacred", arabic: "مكة المكرمة", summary: "The direction of every Salah and the destination of Hajj and Umrah.", significance: "Al-Masjid al-Haram surrounds the Kaaba, the first House established for worship. Hajj rites centre on Makkah and the nearby sacred sites during appointed days.", places: ["Al-Masjid al-Haram and the Kaaba", "Safa and Marwah", "Mina, Arafat and Muzdalifah during Hajj"], etiquette: "Enter the Haram with humility, protect other worshippers’ space, follow crowd instructions and avoid obstructive photography.", planning: "Hajj, Umrah, visa and permit rules change. Check the official Nusuk and Ministry of Hajj and Umrah requirements before booking.", source: "Quran 3:96–97; official Nusuk guidance" },
  { slug: "madinah", name: "Al-Madinah al-Munawwarah", country: "Saudi Arabia", region: "Middle East", category: "Sacred", arabic: "المدينة المنورة", summary: "The city of the Prophet ﷺ and home of Al-Masjid an-Nabawi.", significance: "The Prophet Muhammad ﷺ migrated to Madinah, built a community there and is buried beside Abu Bakr and Umar رضي الله عنهما in the chamber adjoining the mosque.", places: ["Al-Masjid an-Nabawi", "Masjid Quba", "Mount Uhud and its martyrs’ area"], etiquette: "Lower the voice, give Salam respectfully, avoid pushing, and follow the mosque’s designated prayer and visit routes.", planning: "Use official booking and permit information. Heat, walking distance and crowd density should be considered for older or disabled visitors.", source: "Sahih al-Bukhari reports on Madinah; official Nusuk guidance" },
  { slug: "al-quds", name: "Al-Quds / Jerusalem", country: "Palestine", region: "Middle East", category: "Sacred", arabic: "القدس", summary: "Home of Al-Masjid al-Aqsa, Islam’s third sacred mosque.", significance: "The Quran connects the Sacred Mosque with the Furthest Mosque in the account of Al-Isra. The wider sanctuary has centuries of Islamic, Christian and Jewish history.", places: ["Al-Masjid al-Aqsa sanctuary", "Dome of the Rock", "Historic Old City quarters"], etiquette: "Respect worship, local communities and the holiness of the sanctuary; never treat a complex political reality as a photo backdrop.", planning: "Entry conditions and local security can change quickly. Verify current official and trusted local guidance before travel.", source: "Quran 17:1; UNESCO Old City of Jerusalem documentation" },
  { slug: "ajmer", name: "Ajmer Sharif", country: "India", region: "South Asia", category: "Sufi heritage", summary: "A major South Asian centre associated with Khwaja Moinuddin Chishti رحمه الله.", significance: "The Dargah in Ajmer preserves the memory of the Chishti teacher known as Gharib Nawaz and has long received visitors from many backgrounds.", places: ["Dargah Ajmer Sharif", "Akbari Masjid", "Adhai Din ka Jhonpra heritage area"], etiquette: "Dress modestly, keep the prayer areas clear, follow the Dargah administration and do not pressure or mislead other visitors.", planning: "The lanes can be crowded. Keep belongings secure, agree transport fares and check accessibility before entering the historic core.", source: "Rajasthan Tourism: Ajmer Sharif Dargah" },
  { slug: "istanbul", name: "Historic Istanbul", country: "Türkiye", region: "Europe & Asia", category: "Islamic history", summary: "An Ottoman capital shaped by mosques, waqf complexes, scholarship and craft.", significance: "Istanbul’s historic areas preserve major Byzantine and Ottoman monuments. The Süleymaniye complex is a leading example of Ottoman religious and civic architecture.", places: ["Süleymaniye Mosque complex", "Sultanahmet Mosque", "Historic peninsula and Topkapı area"], etiquette: "Mosques remain active places of worship. Observe prayer closures, modest dress and quiet conduct.", planning: "Use public transport around the historic peninsula and leave extra time for queues, hills and Friday-prayer access.", source: "UNESCO Historic Areas of Istanbul" },
  { slug: "cairo", name: "Historic Cairo", country: "Egypt", region: "North Africa", category: "Learning", summary: "One of the world’s oldest Islamic cities, rich in mosques and madrasas.", significance: "Founded in the 10th century, Historic Cairo became a major centre of the Islamic world and preserves a dense urban fabric of religious and civic monuments.", places: ["Al-Azhar Mosque and learning precinct", "Sultan Hasan and Al-Rifa‘i mosques", "Al-Muizz Street monuments"], etiquette: "Ask before photographing people, respect active classes and prayer, and use a responsible guide in fragile heritage interiors.", planning: "Traffic, heat and uneven historic streets affect timing. Group nearby monuments rather than crossing the city repeatedly.", source: "UNESCO Historic Cairo" },
  { slug: "fez", name: "Medina of Fez", country: "Morocco", region: "North Africa", category: "Learning", summary: "A living medina known for scholarship, craft and historic religious architecture.", significance: "Founded in the 9th century, Fez retains an important cultural and spiritual role. Its medina preserves madrasas, mosques, residences, markets and fountains.", places: ["Al-Qarawiyyin precinct", "Bou Inania Madrasa", "Fez el-Bali craft quarters"], etiquette: "Respect residents in the narrow lanes, avoid blocking workshops and confirm which religious spaces admit non-worship visitors.", planning: "The medina is complex and mostly pedestrian. Use a licensed guide when needed and wear shoes suitable for steep, uneven lanes.", source: "UNESCO Medina of Fez" },
  { slug: "bukhara", name: "Historic Bukhara", country: "Uzbekistan", region: "Central Asia", category: "Learning", summary: "A Silk Road city that served as a major centre of Islamic culture.", significance: "Bukhara’s largely intact historic centre preserves medieval urban fabric, madrasas, mosques and the 10th-century Ismail Samani mausoleum.", places: ["Poi Kalyan complex", "Ismail Samani mausoleum", "Lyabi-Hauz and historic madrasas"], etiquette: "Keep active worship spaces quiet and distinguish devotional sites from museums when planning your visit.", planning: "Summers are hot and winters cold. Check train schedules and opening times before building a tight itinerary.", source: "UNESCO Historic Centre of Bukhara" },
  { slug: "samarkand", name: "Samarkand", country: "Uzbekistan", region: "Central Asia", category: "Islamic history", summary: "A crossroads of cultures with monumental Timurid architecture.", significance: "Samarkand flourished during the Timurid period. Its celebrated ensembles influenced Islamic architecture far beyond Central Asia.", places: ["Registan madrasas", "Bibi-Khanum Mosque", "Shah-i-Zinda and Gur-e-Amir ensembles"], etiquette: "Observe the different rules of active mosques, mausoleums and ticketed heritage sites; dress and behave respectfully in each.", planning: "Distances between ensembles are walkable in parts but not all. Plan around heat and evening illumination times.", source: "UNESCO Samarkand – Crossroad of Cultures" },
  { slug: "konya", name: "Konya", country: "Türkiye", region: "Anatolia", category: "Sufi heritage", summary: "A city closely associated with Mawlana Jalaluddin Rumi رحمه الله.", significance: "Konya was a Seljuk centre of learning and is widely visited for the Mevlana complex and the literary and spiritual legacy associated with Rumi.", places: ["Mevlana Museum complex", "Alaeddin Mosque and hill", "Karatay Madrasa"], etiquette: "Treat tomb and mosque areas as devotional spaces, not performance sets. Respect local guidance during ceremonies.", planning: "Winters can be cold. Confirm event dates and ticket arrangements independently before planning around annual gatherings.", source: "Türkiye cultural heritage and museum documentation" },
];
