// Interface copy only. Quran translations and reviewed educational text have their own sources.
export const DAILY_UI_COPY: Record<string, [string, string]> = {
  "Your browser could not save this change. Free some storage or allow site storage, then try again.": ["ब्राउज़र यह बदलाव सहेज नहीं पाया। स्टोरेज खाली करें या साइट स्टोरेज की अनुमति दें और फिर कोशिश करें।", "آپ کا براؤزر یہ تبدیلی محفوظ نہیں کر سکا۔ کچھ جگہ خالی کریں یا سائٹ اسٹوریج کی اجازت دیں، پھر کوشش کریں۔"],
  "Try a topic, Surah name, dua, or verse reference such as 2:255.": ["विषय, सूरह का नाम, दुआ या 2:255 जैसी आयत खोजें।", "موضوع، سورہ کا نام، دعا یا 2:255 جیسا آیت کا حوالہ تلاش کریں۔"],
  "Search is temporarily unavailable. Please try again.": ["खोज अभी उपलब्ध नहीं है। फिर कोशिश करें।", "تلاش عارضی طور پر دستیاب نہیں۔ دوبارہ کوشش کریں۔"],
  "Try again": ["फिर कोशिश करें", "دوبارہ کوشش کریں"],
  "Dismiss": ["बंद करें", "بند کریں"],
  "Primary navigation": ["मुख्य नेविगेशन", "بنیادی نیویگیشن"],
  "OFFLINE DOWNLOADS": ["ऑफ़लाइन डाउनलोड", "آف لائن ڈاؤن لوڈ"],
  "Choose · Download · Read": ["चुनें · डाउनलोड करें · पढ़ें", "منتخب کریں · ڈاؤن لوڈ کریں · پڑھیں"],
  "SAVED": ["सहेजा हुआ", "محفوظ"],
  "Your private NOOR collection": ["नूर में आपका निजी संग्रह", "نور میں آپ کا نجی مجموعہ"],
  "Read wherever you are": ["जहाँ भी हों, पढ़ें", "جہاں بھی ہوں، پڑھیں"],
  "Manage Quran downloads and their storage on this device.": ["इस डिवाइस पर क़ुरआन डाउनलोड और स्टोरेज प्रबंधित करें।", "اس آلے پر قرآن کے ڈاؤن لوڈ اور اسٹوریج کا انتظام کریں۔"],
  "NOOR is running as an installed app.": ["नूर इंस्टॉल किए गए ऐप के रूप में चल रहा है।", "نور انسٹال شدہ ایپ کے طور پر چل رہا ہے۔"],
  "Installation accepted.": ["इंस्टॉलेशन स्वीकार किया गया।", "تنصیب قبول کر لی گئی۔"],
  "You can install later from your browser menu.": ["बाद में ब्राउज़र मेनू से इंस्टॉल कर सकते हैं।", "آپ بعد میں براؤزر کے مینو سے انسٹال کر سکتے ہیں۔"],
  "Use your browser menu to install NOOR.": ["नूर इंस्टॉल करने के लिए ब्राउज़र मेनू खोलें।", "نور انسٹال کرنے کے لیے براؤزر کا مینو کھولیں۔"],
  "Open NOOR in Safari → Share → Add to Home Screen → Add.": ["Safari में नूर खोलें → शेयर → होम स्क्रीन पर जोड़ें → जोड़ें।", "Safari میں نور کھولیں ← شیئر ← ہوم اسکرین پر شامل کریں ← شامل کریں۔"],
  "Android / desktop": ["Android / कंप्यूटर", "Android / کمپیوٹر"],
  "Open your browser menu → Install app or Add to Home screen. If unavailable, keep a bookmark.": ["ब्राउज़र मेनू खोलें → ऐप इंस्टॉल करें या होम स्क्रीन पर जोड़ें। विकल्प न मिले तो बुकमार्क रखें।", "براؤزر کا مینو کھولیں ← ایپ انسٹال کریں یا ہوم اسکرین پر شامل کریں۔ اختیار نہ ملے تو بک مارک محفوظ کریں۔"],
  "Installation gives you an app shortcut. Download each Quran selection separately before going offline.": ["इंस्टॉल करने से ऐप का शॉर्टकट मिलता है। ऑफ़लाइन जाने से पहले हर चुनी सूरह अलग से डाउनलोड करें।", "انسٹال کرنے سے ایپ کا شارٹ کٹ ملتا ہے۔ آف لائن جانے سے پہلے ہر منتخب سورت الگ ڈاؤن لوڈ کریں۔"],
  "Download while connected. Arabic and the selected translation are included. Audio is optional and may use substantial storage. Study tools such as tafsir and word meanings still require a connection.": ["इंटरनेट चालू रहते हुए डाउनलोड करें। अरबी और चुना अनुवाद शामिल हैं। ऑडियो वैकल्पिक है और अधिक स्टोरेज ले सकता है। तफ़सीर और शब्दार्थ के लिए इंटरनेट चाहिए।", "انٹرنیٹ سے منسلک رہتے ہوئے ڈاؤن لوڈ کریں۔ عربی اور منتخب ترجمہ شامل ہیں۔ آڈیو اختیاری ہے اور زیادہ اسٹوریج لے سکتی ہے۔ تفسیر اور لفظی معانی کے لیے انٹرنیٹ ضروری ہے۔"],
  "Download removed.": ["डाउनलोड हटा दिया गया।", "ڈاؤن لوڈ ہٹا دیا گیا۔"],
  "Unable to remove download.": ["डाउनलोड नहीं हट सका।", "ڈاؤن لوڈ نہیں ہٹ سکا۔"],
  "Downloading… Keep this page open.": ["डाउनलोड हो रहा है… यह पेज खुला रखें।", "ڈاؤن لوڈ جاری ہے… یہ صفحہ کھلا رکھیں۔"],
  "Download complete. You can now read this selection offline.": ["डाउनलोड पूरा हुआ। अब इसे ऑफ़लाइन पढ़ सकते हैं।", "ڈاؤن لوڈ مکمل ہوا۔ اب اسے آف لائن پڑھ سکتے ہیں۔"],
  "Download cancelled.": ["डाउनलोड रद्द हुआ।", "ڈاؤن لوڈ منسوخ ہوا۔"],
  "Download failed.": ["डाउनलोड विफल हुआ।", "ڈاؤن لوڈ ناکام ہوا۔"],
  "Download progress": ["डाउनलोड की प्रगति", "ڈاؤن لوڈ کی پیش رفت"],
  "Preparing offline support…": ["ऑफ़लाइन सुविधा तैयार हो रही है…", "آف لائن سہولت تیار ہو رہی ہے…"],
  "Downloading Arabic and translation…": ["अरबी और अनुवाद डाउनलोड हो रहे हैं…", "عربی اور ترجمہ ڈاؤن لوڈ ہو رہے ہیں…"],
  "Downloading recitation…": ["तिलावत डाउनलोड हो रही है…", "تلاوت ڈاؤن لوڈ ہو رہی ہے…"],
  "Preparing pages for offline reading…": ["ऑफ़लाइन पढ़ने के लिए पेज तैयार हो रहे हैं…", "آف لائن پڑھنے کے لیے صفحات تیار ہو رہے ہیں…"],
  "Saving download…": ["डाउनलोड सहेजा जा रहा है…", "ڈاؤن لوڈ محفوظ ہو رہا ہے…"],
  "Download complete": ["डाउनलोड पूरा हुआ", "ڈاؤن لوڈ مکمل ہوا"],
  "{used} MB used of {quota} MB available to this website.": ["वेबसाइट के लिए उपलब्ध {quota} MB में से {used} MB इस्तेमाल हुआ।", "ویب سائٹ کے لیے دستیاب {quota} MB میں سے {used} MB استعمال ہوئے۔"],
  "Your browser does not expose a storage estimate.": ["ब्राउज़र स्टोरेज का अनुमान नहीं देता।", "براؤزر اسٹوریج کا تخمینہ فراہم نہیں کرتا۔"],
  "Persistent storage granted.": ["स्थायी स्टोरेज की अनुमति मिली।", "مستقل اسٹوریج کی اجازت مل گئی۔"],
  "Downloads may be cleared by your browser.": ["ब्राउज़र डाउनलोड मिटा सकता है।", "براؤزر ڈاؤن لوڈ صاف کر سکتا ہے۔"],
  "Persistent storage granted. Your device settings can still clear downloads.": ["स्थायी स्टोरेज की अनुमति मिली। डिवाइस सेटिंग से डाउनलोड फिर भी मिट सकते हैं।", "مستقل اسٹوریج کی اجازت مل گئی۔ آلے کی ترتیبات سے ڈاؤن لوڈ اب بھی صاف ہو سکتے ہیں۔"],
  "Persistent storage was not granted. Keep a backup of private notes.": ["स्थायी स्टोरेज की अनुमति नहीं मिली। निजी नोट्स का बैकअप रखें।", "مستقل اسٹوریج کی اجازت نہیں ملی۔ نجی نوٹس کا بیک اپ محفوظ رکھیں۔"],
  "Persistent storage is unavailable in this browser.": ["इस ब्राउज़र में स्थायी स्टोरेज उपलब्ध नहीं है।", "اس براؤزر میں مستقل اسٹوریج دستیاب نہیں ہے۔"],
  "Missing downloads: {titles}. Remove and download them again while connected.": ["ये डाउनलोड नहीं मिले: {titles}। इन्हें हटाकर इंटरनेट चालू रहते हुए फिर डाउनलोड करें।", "یہ ڈاؤن لوڈ نہیں ملے: {titles}۔ انہیں ہٹا کر انٹرنیٹ سے منسلک رہتے ہوئے دوبارہ ڈاؤن لوڈ کریں۔"],
  "{count} selections checked. All indexed reading and audio files are present.": ["{count} डाउनलोड जाँचे गए। सूची की सभी पढ़ने और ऑडियो फ़ाइलें मौजूद हैं।", "{count} ڈاؤن لوڈ جانچے گئے۔ فہرست کی تمام پڑھنے اور آڈیو فائلیں موجود ہیں۔"],
  "Download verification is unavailable.": ["डाउनलोड की जाँच उपलब्ध नहीं है।", "ڈاؤن لوڈ کی جانچ دستیاب نہیں ہے۔"],
  "{count} selections · {size} MB. Browser storage may be cleared by your device.": ["{count} डाउनलोड · {size} MB। डिवाइस ब्राउज़र का स्टोरेज साफ़ कर सकता है।", "{count} ڈاؤن لوڈ · {size} MB۔ آلہ براؤزر کی اسٹوریج صاف کر سکتا ہے۔"],
  "Reading + audio": ["पढ़ना + ऑडियो", "پڑھنا + آڈیو"],
  "Open downloaded Surah": ["डाउनलोड की सूरह खोलें", "ڈاؤن لوڈ شدہ سورت کھولیں"],
  "No Quran selections downloaded yet.": ["अभी कोई सूरह डाउनलोड नहीं की गई।", "ابھی کوئی سورت ڈاؤن لوڈ نہیں کی گئی۔"],
  "Daily duas are included in the prepared offline pages.": ["तैयार किए गए ऑफ़लाइन पेजों में रोज़ाना दुआएँ शामिल हैं।", "تیار شدہ آف لائن صفحات میں روزانہ کی دعائیں شامل ہیں۔"],
  "Open daily duas": ["रोज़ाना दुआएँ खोलें", "روزانہ کی دعائیں کھولیں"],
  "Fajr": ["फ़ज्र", "فجر"], "Dhuhr": ["ज़ुहर", "ظہر"], "Asr": ["अस्र", "عصر"], "Maghrib": ["मग़रिब", "مغرب"], "Isha": ["इशा", "عشاء"],
  "Permission": ["अनुमति", "اجازت"], "Delivery": ["सूचना पहुँचाना", "اطلاع کی ترسیل"], "off": ["बंद", "بند"], "open prayer page": ["नमाज़ का पेज खुला है", "نماز کا صفحہ کھلا ہے"],
  "Checking support…": ["ब्राउज़र की सुविधा जाँची जा रही है…", "براؤزر کی سہولت جانچی جا رہی ہے…"], "default": ["अनुमति नहीं माँगी गई", "اجازت نہیں مانگی گئی"], "granted": ["अनुमति मिली", "اجازت مل گئی"], "denied": ["अनुमति नहीं मिली", "اجازت نہیں ملی"], "unsupported": ["सुविधा उपलब्ध नहीं है", "سہولت دستیاب نہیں ہے"],
  "{minutes} minutes before": ["{minutes} मिनट पहले", "{minutes} منٹ پہلے"],
  "Reminder preferences could not be saved.": ["याद दिलाने की पसंद सहेजी नहीं जा सकी।", "یاد دہانی کی ترجیحات محفوظ نہیں ہو سکیں۔"],
  "Browser alerts are unavailable. Use calendar reminders.": ["ब्राउज़र सूचनाएँ उपलब्ध नहीं हैं। कैलेंडर की याद दिलाने वाली सुविधा इस्तेमाल करें।", "براؤزر کی اطلاعات دستیاب نہیں ہیں۔ کیلنڈر کی یاد دہانیاں استعمال کریں۔"],
  "Reload NOOR once to prepare notifications, or use calendar reminders.": ["सूचनाएँ तैयार करने के लिए नूर फिर खोलें या कैलेंडर इस्तेमाल करें।", "اطلاعات تیار کرنے کے لیے نور دوبارہ کھولیں یا کیلنڈر استعمال کریں۔"],
  "Your browser could not store reminder delivery status. Alerts are paused.": ["ब्राउज़र सूचना पहुँचने की स्थिति सहेज नहीं सका। सूचनाएँ रुकी हुई हैं।", "براؤزر اطلاع کی ترسیل کی حالت محفوظ نہیں کر سکا۔ اطلاعات عارضی طور پر رکی ہوئی ہیں۔"],
  "This browser does not support alerts. Use the calendar option.": ["इस ब्राउज़र में सूचनाएँ नहीं चलतीं। कैलेंडर विकल्प इस्तेमाल करें।", "یہ براؤزر اطلاعات کی سہولت نہیں دیتا۔ کیلنڈر کا اختیار استعمال کریں۔"],
  "Alerts enabled while this prayer page stays open. Send a test to check delivery.": ["यह नमाज़ पेज खुला रहने तक सूचनाएँ चालू हैं। जाँचने के लिए परीक्षण सूचना भेजें।", "نماز کا یہ صفحہ کھلا رہنے تک اطلاعات فعال ہیں۔ جانچنے کے لیے آزمائشی اطلاع بھیجیں۔"],
  "Permission was not granted. You can use calendar reminders or change browser permissions.": ["अनुमति नहीं मिली। कैलेंडर इस्तेमाल करें या ब्राउज़र की अनुमति बदलें।", "اجازت نہیں ملی۔ کیلنڈر استعمال کریں یا براؤزر کی اجازت تبدیل کریں۔"],
  "Permission could not be requested. On iPhone, install NOOR to your Home Screen first.": ["अनुमति नहीं माँगी जा सकी। iPhone पर पहले नूर को होम स्क्रीन पर इंस्टॉल करें।", "اجازت نہیں مانگی جا سکی۔ iPhone پر پہلے نور کو ہوم اسکرین پر انسٹال کریں۔"],
  "Test notification sent. Check your device's notification settings if it does not appear.": ["परीक्षण सूचना भेजी गई। न दिखे तो डिवाइस की सूचना सेटिंग जाँचें।", "آزمائشی اطلاع بھیجی گئی۔ نظر نہ آئے تو آلے کی اطلاع کی ترتیبات جانچیں۔"],
  "Test failed.": ["परीक्षण विफल हुआ।", "آزمائش ناکام ہوئی۔"], "Alert could not be delivered.": ["सूचना नहीं पहुँच सकी।", "اطلاع نہیں پہنچ سکی۔"],
  "Calendar export requested. Import the file into your calendar and check its alert settings. These are today's times only; export a new schedule for another day.": ["कैलेंडर फ़ाइल डाउनलोड का अनुरोध किया गया। इसे कैलेंडर में जोड़कर सूचना सेटिंग जाँचें। समय सिर्फ आज के हैं; दूसरे दिन नई फ़ाइल लें।", "کیلنڈر فائل ڈاؤن لوڈ کرنے کی درخواست کی گئی۔ اسے کیلنڈر میں شامل کرکے اطلاع کی ترتیبات جانچیں۔ اوقات صرف آج کے ہیں؛ دوسرے دن نئی فائل حاصل کریں۔"],
  "NOOR test reminder": ["नूर परीक्षण सूचना", "نور آزمائشی اطلاع"],
  "Your browser can display NOOR prayer reminders.": ["आपका ब्राउज़र नूर की नमाज़ सूचनाएँ दिखा सकता है।", "آپ کا براؤزر نور کی نماز کی یاد دہانیاں دکھا سکتا ہے۔"],
  "Prayer time": ["नमाज़ का समय", "نماز کا وقت"], "Starts {date}": ["शुरुआत: {date}", "آغاز: {date}"],
  "Choose a valid date and plan.": ["सही तारीख और योजना चुनें।", "درست تاریخ اور منصوبہ منتخب کریں۔"],
  "Your browser could not save this plan.": ["ब्राउज़र यह योजना सहेज नहीं सका।", "براؤزر یہ منصوبہ محفوظ نہیں کر سکا۔"],
  "Quran plan completion": ["क़ुरआन योजना की प्रगति", "قرآن منصوبے کی پیش رفت"],
  "Choose location": ["जगह चुनें", "مقام منتخب کریں"], "Search city or postal code": ["शहर या पोस्टल कोड खोजें", "شہر یا پوسٹل کوڈ تلاش کریں"],
  "Quick city selection": ["शहर जल्दी चुनें", "شہر فوراً منتخب کریں"], "Choose a preset city": ["सूची से शहर चुनें", "فہرست سے شہر منتخب کریں"],
  "Use my location": ["मेरी जगह इस्तेमाल करें", "میرا مقام استعمال کریں"], "Locating…": ["जगह पता कर रहे हैं…", "مقام معلوم کیا جا رہا ہے…"],
  "Searching cities…": ["शहर खोजे जा रहे हैं…", "شہر تلاش کیے جا رہے ہیں…"], "Selected": ["चुना गया", "منتخب"],
  "Select your city below.": ["नीचे अपना शहर चुनें।", "نیچے اپنا شہر منتخب کریں۔"], "No cities found. Try a city and country.": ["कोई शहर नहीं मिला। शहर और देश लिखें।", "کوئی شہر نہیں ملا۔ شہر اور ملک لکھیں۔"],
  "City search unavailable.": ["शहर की खोज उपलब्ध नहीं है।", "شہر کی تلاش دستیاب نہیں ہے۔"],
  "Device location unavailable. Search for your city.": ["डिवाइस की जगह उपलब्ध नहीं है। अपना शहर खोजें।", "آلے کا مقام دستیاب نہیں ہے۔ اپنا شہر تلاش کریں۔"],
  "Location permission unavailable. Search for your city instead.": ["जगह की अनुमति उपलब्ध नहीं है। अपना शहर खोजें।", "مقام کی اجازت دستیاب نہیں ہے۔ اپنا شہر تلاش کریں۔"],
  "default city — choose your location": ["डिफ़ॉल्ट शहर — अपनी जगह चुनें", "پہلے سے منتخب شہر — اپنا مقام منتخب کریں"], "selected location": ["चुनी हुई जगह", "منتخب مقام"],
  "accuracy about {meters} m": ["लगभग {meters} मीटर की सटीकता", "تقریباً {meters} میٹر کی درستگی"],
  "City search: Open-Meteo / GeoNames. Search terms are sent to the provider.": ["शहर की खोज: Open-Meteo / GeoNames। खोज के शब्द प्रदाता को भेजे जाते हैं।", "شہر کی تلاش: Open-Meteo / GeoNames۔ تلاش کے الفاظ فراہم کنندہ کو بھیجے جاتے ہیں۔"],
  "Account sync": ["खाते का सिंक", "اکاؤنٹ کی ہم آہنگی"], "Optional account sync": ["खाते का वैकल्पिक सिंक", "اکاؤنٹ کی اختیاری ہم آہنگی"],
  "Nothing is uploaded unless you press Sync.": ["सिंक दबाए बिना कुछ अपलोड नहीं होता।", "ہم آہنگی دبائے بغیر کچھ اپ لوڈ نہیں ہوتا۔"],
  "Account sync is unavailable until secure production sign-in is connected.": ["सुरक्षित साइन-इन जुड़ने तक खाते का सिंक उपलब्ध नहीं है।", "محفوظ سائن اِن منسلک ہونے تک اکاؤنٹ کی ہم آہنگی دستیاب نہیں ہے۔"],
  "Securely checking your account collection…": ["आपके खाते का संग्रह सुरक्षित तरीके से जाँचा जा रहा है…", "آپ کے اکاؤنٹ کا مجموعہ محفوظ طریقے سے جانچا جا رہا ہے…"],
  "Sign in to sync this collection across devices.": ["डिवाइसों में संग्रह सिंक करने के लिए साइन इन करें।", "آلات میں مجموعہ ہم آہنگ کرنے کے لیے سائن اِن کریں۔"],
  "Account sync is not available yet.": ["खाते का सिंक अभी उपलब्ध नहीं है।", "اکاؤنٹ کی ہم آہنگی ابھی دستیاب نہیں ہے۔"],
  "Secure account sync is not configured.": ["सुरक्षित खाते का सिंक सेट अप नहीं हुआ है।", "محفوظ اکاؤنٹ کی ہم آہنگی ترتیب نہیں دی گئی۔"],
  "Account sync is temporarily unavailable.": ["खाते का सिंक अभी उपलब्ध नहीं है।", "اکاؤنٹ کی ہم آہنگی عارضی طور پر دستیاب نہیں ہے۔"],
  "Unable to save your account collection.": ["खाते का संग्रह सहेजा नहीं जा सका।", "اکاؤنٹ کا مجموعہ محفوظ نہیں ہو سکا۔"],
  "Sync returned no account data.": ["सिंक से खाते का डेटा नहीं मिला।", "ہم آہنگی سے اکاؤنٹ کا ڈیٹا نہیں ملا۔"],
  "Synced securely at {time}.": ["{time} पर सुरक्षित सिंक हुआ।", "{time} پر محفوظ ہم آہنگی ہوئی۔"],
  "{count} note conflicts kept this device’s text. Reload the reader to see synced notes.": ["{count} नोट्स में अंतर था; इस डिवाइस का पाठ रखा गया। सिंक किए नोट्स देखने के लिए रीडर फिर खोलें।", "{count} نوٹس میں اختلاف تھا؛ اس آلے کا متن محفوظ رکھا گیا۔ ہم آہنگ نوٹس دیکھنے کے لیے ریڈر دوبارہ کھولیں۔"],
  "Last successful sync": ["पिछला सफल सिंक", "آخری کامیاب ہم آہنگی"],
  "Merge saved items, Quran progress, preferences and completion plans. Nothing is uploaded automatically. Downloads and precise location stay on your device.": ["सहेजी चीज़ें, क़ुरआन की प्रगति, पसंद और योजनाएँ मिलाएँ। कुछ अपने आप अपलोड नहीं होता। डाउनलोड और सटीक जगह डिवाइस पर रहते हैं।", "محفوظ چیزیں، قرآن کی پیش رفت، ترجیحات اور منصوبے یکجا کریں۔ کچھ خود بخود اپ لوڈ نہیں ہوتا۔ ڈاؤن لوڈ اور درست مقام آلے پر رہتے ہیں۔"],
  "I agree to sync my saved items and progress to my account.": ["मैं अपनी सहेजी चीज़ें और प्रगति खाते में सिंक करने की सहमति देता/देती हूँ।", "میں اپنی محفوظ چیزیں اور پیش رفت اکاؤنٹ میں ہم آہنگ کرنے پر رضامند ہوں۔"],
  "Include my private Quran notes (optional).": ["मेरे निजी क़ुरआन नोट्स शामिल करें (वैकल्पिक)।", "میرے نجی قرآن نوٹس شامل کریں (اختیاری)۔"],
  "Use Export backup below to transfer your private data until account services are connected.": ["खाता सेवाएँ जुड़ने तक निजी डेटा ले जाने के लिए नीचे बैकअप निर्यात करें।", "اکاؤنٹ کی خدمات منسلک ہونے تک نجی ڈیٹا منتقل کرنے کے لیے نیچے بیک اپ برآمد کریں۔"],
  "Content review and sources": ["सामग्री की समीक्षा और स्रोत", "مواد کا جائزہ اور مصادر"], "Not configured": ["सेट अप नहीं हुआ", "ترتیب نہیں دی گئی"], "Sign in": ["साइन इन करें", "سائن اِن کریں"],
  "Syncing…": ["सिंक हो रहा है…", "ہم آہنگی جاری ہے…"], "Sync again": ["फिर सिंक करें", "دوبارہ ہم آہنگ کریں"], "Sync across devices": ["डिवाइसों में सिंक करें", "آلات میں ہم آہنگ کریں"],
  "Your private data": ["आपका निजी डेटा", "آپ کا نجی ڈیٹا"], "Export backup": ["बैकअप निर्यात करें", "بیک اپ برآمد کریں"], "Restore backup": ["बैकअप बहाल करें", "بیک اپ بحال کریں"],
  "Export or restore bookmarks, notes and reading/Qaza progress. Accounts and location are excluded.": ["बुकमार्क, नोट्स और पढ़ने/क़ज़ा की प्रगति का बैकअप लें या बहाल करें। खाते और जगह शामिल नहीं हैं।", "بک مارکس، نوٹس اور پڑھنے/قضا کی پیش رفت کا بیک اپ بنائیں یا بحال کریں۔ اکاؤنٹ اور مقام شامل نہیں ہیں۔"],
  "Delete local personal data": ["डिवाइस का निजी डेटा हटाएँ", "آلے کا نجی ڈیٹا حذف کریں"], "Confirm deletion": ["हटाने की पुष्टि करें", "حذف کرنے کی تصدیق کریں"],
  "Delete local bookmarks, notes, counters and plans? Export first if you want to keep them. This does not delete cloud data or offline downloads.": ["डिवाइस के बुकमार्क, नोट्स, काउंटर और योजनाएँ हटाएँ? रखना हो तो पहले बैकअप लें। क्लाउड डेटा और ऑफ़लाइन डाउनलोड नहीं हटेंगे।", "آلے کے بک مارکس، نوٹس، شمار اور منصوبے حذف کریں؟ محفوظ رکھنے کے لیے پہلے بیک اپ بنائیں۔ کلاؤڈ ڈیٹا اور آف لائن ڈاؤن لوڈ حذف نہیں ہوں گے۔"],
  "Backup downloaded. It contains private notes and progress; keep it safe.": ["बैकअप डाउनलोड हुआ। इसमें निजी नोट्स और प्रगति हैं; इसे सुरक्षित रखें।", "بیک اپ ڈاؤن لوڈ ہوا۔ اس میں نجی نوٹس اور پیش رفت ہیں؛ اسے محفوظ رکھیں۔"],
  "Unable to export browser data.": ["ब्राउज़र का डेटा निर्यात नहीं हो सका।", "براؤزر کا ڈیٹا برآمد نہیں ہو سکا۔"], "Backup exceeds the 1 MB limit.": ["बैकअप 1 MB की सीमा से बड़ा है।", "بیک اپ 1 MB کی حد سے بڑا ہے۔"],
  "Backup restored. Reload an open reader to refresh its notes. Matching local entries were replaced.": ["बैकअप बहाल हुआ। खुले रीडर में नोट्स देखने के लिए पेज फिर खोलें। मेल खाने वाली स्थानीय प्रविष्टियाँ बदली गईं।", "بیک اپ بحال ہوا۔ کھلے ریڈر میں نوٹس دیکھنے کے لیے صفحہ دوبارہ کھولیں۔ مماثل مقامی اندراجات بدل دیے گئے۔"],
  "Backup could not be restored.": ["बैकअप बहाल नहीं हो सका।", "بیک اپ بحال نہیں ہو سکا۔"], "Local personal data deleted.": ["डिवाइस का निजी डेटा हटाया गया।", "آلے کا نجی ڈیٹا حذف ہوا۔"],
  "PRIVATE ON THIS DEVICE": ["इस डिवाइस पर निजी", "اس آلے پر نجی"], "Your saved collection": ["आपका सहेजा संग्रह", "آپ کا محفوظ مجموعہ"],
  "Keep verses, Surahs, duas, Darood and glossary words together. They remain available after refresh on this browser.": ["आयतें, सूरह, दुआएँ, दुरूद और शब्दावली एक जगह रखें। इस ब्राउज़र में पेज फिर खोलने पर भी मिलेंगे।", "آیات، سورتیں، دعائیں، درود اور لغت کے الفاظ ایک جگہ محفوظ کریں۔ اس براؤزر میں صفحہ دوبارہ کھولنے پر بھی دستیاب رہیں گے۔"],
  "item": ["चीज़", "چیز"], "items": ["चीज़ें", "چیزیں"], "saved": ["सहेजा हुआ", "محفوظ"], "All": ["सभी", "سب"], "Darood": ["दुरूद", "درود"], "Glossary": ["शब्दावली", "لغت"],
  "Filter saved items": ["सहेजी चीज़ें छाँटें", "محفوظ چیزیں چھانٹیں"], "Nothing saved yet": ["अभी कुछ सहेजा नहीं है", "ابھی کچھ محفوظ نہیں"],
  "Tap Save or Bookmark anywhere in NOOR and it will appear here.": ["नूर में कहीं भी सहेजें या बुकमार्क दबाएँ; वह यहाँ दिखेगा।", "نور میں کہیں بھی محفوظ کریں یا بک مارک دبائیں؛ وہ یہاں نظر آئے گا۔"],
  "Read Quran": ["क़ुरआन पढ़ें", "قرآن پڑھیں"], "Browse Darood": ["दुरूद देखें", "درود دیکھیں"], "Open Glossary": ["शब्दावली खोलें", "لغت کھولیں"],
  "SAVED SURAH": ["सहेजी सूरह", "محفوظ سورت"], "SAVED AYAH": ["सहेजी आयत", "محفوظ آیت"], "Open Surah": ["सूरह खोलें", "سورت کھولیں"], "Open Ayah": ["आयत खोलें", "آیت کھولیں"], "Remove": ["हटाएँ", "ہٹائیں"],
  "Continue reading from the full Quran reader.": ["क़ुरआन रीडर में पढ़ना जारी रखें।", "قرآن ریڈر میں پڑھنا جاری رکھیں۔"], "Open the exact saved verse in the reader.": ["सहेजी गई आयत रीडर में खोलें।", "محفوظ آیت ریڈر میں کھولیں۔"],
  "Daily Duas": ["रोज़ाना दुआएँ", "روزانہ کی دعائیں"], "Darood Sharif": ["दुरूद शरीफ़", "درود شریف"], "Islamic Glossary": ["इस्लामी शब्दावली", "اسلامی لغت"],
  "Open dua": ["दुआ खोलें", "دعا کھولیں"], "Open Darood": ["दुरूद खोलें", "درود کھولیں"], "Open word": ["शब्द खोलें", "لفظ کھولیں"], "excerpt": ["अंश", "اقتباس"],
  "Saved items stay in this browser by default. Account sync happens only when you choose it.": ["सहेजी चीज़ें सामान्य रूप से इस ब्राउज़र में रहती हैं। खाते में सिंक आपकी पसंद पर होता है।", "محفوظ چیزیں عام طور پر اس براؤزر میں رہتی ہیں۔ اکاؤنٹ کی ہم آہنگی صرف آپ کے انتخاب پر ہوتی ہے۔"],
  "{label} removed from Saved": ["{label} सहेजे संग्रह से हटाया गया", "{label} محفوظ مجموعے سے ہٹا دیا گیا"],
};
Object.assign(DAILY_UI_COPY, {
  "PRAYER TIMES": ["नमाज़ के समय", "نماز کے اوقات"],
  "Today · Monthly schedule · Calculation settings": ["आज · मासिक समय · गणना सेटिंग", "آج · ماہانہ اوقات · حساب کی ترتیبات"],
  "LOCAL PRAYER SCHEDULE": ["स्थानीय नमाज़ के समय", "مقامی نماز کے اوقات"],
  "Prayer times you can verify.": ["नमाज़ के समय जिन्हें आप जाँच सकते हैं।", "نماز کے اوقات جنہیں آپ جانچ سکتے ہیں۔"],
  "One location powers NOOR’s prayer, Qibla and mosque tools. Review the calculation method and always confirm congregation times with your local mosque.": ["एक ही जगह नूर की नमाज़, क़िबला और मस्जिद सुविधाओं में इस्तेमाल होती है। गणना विधि जाँचें और जमाअत का समय स्थानीय मस्जिद से पक्का करें।", "ایک ہی مقام نور کی نماز، قبلہ اور مسجد کی سہولتوں میں استعمال ہوتا ہے۔ حساب کا طریقہ جانچیں اور جماعت کا وقت مقامی مسجد سے ضرور معلوم کریں۔"],
  "NEXT PRAYER": ["अगली नमाज़", "اگلی نماز"], "Loading…": ["लोड हो रहा है…", "لوڈ ہو رہا ہے…"], "Unavailable": ["उपलब्ध नहीं", "دستیاب نہیں"],
  "tomorrow": ["कल", "کل"], "today": ["आज", "آج"], "No verified next-prayer time available.": ["अगली नमाज़ का सत्यापित समय उपलब्ध नहीं है।", "اگلی نماز کا تصدیق شدہ وقت دستیاب نہیں ہے۔"],
  "saved schedule for today": ["आज का सहेजा हुआ समय", "آج کے محفوظ اوقات"], "live schedule": ["वर्तमान समय-सारणी", "تازہ اوقات"], "Select your location below.": ["नीचे अपनी जगह चुनें।", "نیچے اپنا مقام منتخب کریں۔"],
  "Retry prayer times": ["नमाज़ के समय फिर लाएँ", "نماز کے اوقات دوبارہ حاصل کریں"], "Prayer calculation settings": ["नमाज़ की गणना सेटिंग", "نماز کے حساب کی ترتیبات"],
  "Hanafi": ["हनफ़ी", "حنفی"], "Standard": ["मानक", "معیاری"], "No adjustment": ["कोई बदलाव नहीं", "کوئی تبدیلی نہیں"], "Hijri date unavailable": ["हिजरी तारीख उपलब्ध नहीं", "ہجری تاریخ دستیاب نہیں"],
  "MONTHLY SCHEDULE": ["मासिक समय-सारणी", "ماہانہ اوقات"], "Choose a location to load": ["समय लाने के लिए जगह चुनें", "اوقات حاصل کرنے کے لیے مقام منتخب کریں"],
  "Previous month": ["पिछला महीना", "پچھلا مہینہ"], "Next month": ["अगला महीना", "اگلا مہینہ"], "Date": ["तारीख", "تاریخ"],
  "Loading monthly schedule…": ["मासिक समय-सारणी लोड हो रही है…", "ماہانہ اوقات لوڈ ہو رہے ہیں…"], "Retry monthly schedule": ["मासिक समय फिर लाएँ", "ماہانہ اوقات دوبارہ حاصل کریں"],
  "Calculated by AlAdhan / Islamic Network. Times use the selected location’s timezone. Calculated times are not mosque iqamah times; confirm congregation times locally.": ["गणना: AlAdhan / Islamic Network। समय चुनी जगह के समय-क्षेत्र के अनुसार हैं। ये मस्जिद की इक़ामत के समय नहीं हैं; जमाअत का समय स्थानीय तौर पर पक्का करें।", "حساب: AlAdhan / Islamic Network۔ اوقات منتخب مقام کے وقت کے خطے کے مطابق ہیں۔ یہ مسجد کی اقامت کے اوقات نہیں ہیں؛ جماعت کے اوقات مقامی طور پر معلوم کریں۔"],
  "Retrieved": ["प्राप्त किया गया", "حاصل کیا گیا"], "Monthly schedule unavailable.": ["मासिक समय उपलब्ध नहीं है।", "ماہانہ اوقات دستیاب نہیں ہیں۔"],
  "Production sign-in keys are not available to this deployment.": ["इस डिप्लॉयमेंट में प्रोडक्शन साइन-इन की कुंजियाँ उपलब्ध नहीं हैं।", "اس ڈپلائمنٹ میں پروڈکشن سائن اِن کی کلیدیں دستیاب نہیں ہیں۔"],
  "The connected Clerk application still needs production sign-in keys.": ["जुड़े हुए Clerk ऐप के लिए प्रोडक्शन साइन-इन की कुंजियाँ चाहिए।", "منسلک Clerk ایپ کے لیے پروڈکشن سائن اِن کی کلیدیں درکار ہیں۔"],
  "The production database connection is not available to this deployment.": ["इस डिप्लॉयमेंट में प्रोडक्शन डेटाबेस का कनेक्शन उपलब्ध नहीं है।", "اس ڈپلائمنٹ میں پروڈکشن ڈیٹابیس کا کنکشن دستیاب نہیں ہے۔"],
  "Sign-in and database configuration are available.": ["साइन-इन और डेटाबेस का सेटअप उपलब्ध है।", "سائن اِن اور ڈیٹابیس کی ترتیبات دستیاب ہیں۔"],
});
